### ISSUE TITLE
Order Form: Add Items

### ISSUE THREAD

**Issue by ter-chu** [milesressler/mosaic-oms#5]
When opening the form, I add an item and click "Add item"; 

additional fields appear below but my original submission isn't recorded;

when I try to make an entry into the "Item" field with the red asterisk, I'm one able to type one letter and the focus goes away from that field; I need to put the cursor back on that field to the next letter

FYI: I'm not sure if this is a finished product yet - just giving you feedback as I see things
<img width="607" alt="Screenshot 2024-07-17 at 8 28 53 PM" src="https://github.com/user-attachments/assets/0ad97379-1ebc-4d9f-acf8-4b0577934ac4">

@milesressler

**Comment by milesressler** [comment]
yep, very much a work in progress :D
I got kinda stuck on how to handle the items list without it looking too clutters, but I think I have an idea how to handle it.  Will try to tackle that next!

**Comment by milesressler** [comment]
Pushed some changes for the order form - fixes most of the issues. Only main thing i see is lack of validation messages for items, and you can clear the quantity if you backspace on the input box.
